//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountStatu
    {
        public int actstatusId { get; set; }
        public string Description { get; set; }
        public string Abriviation { get; set; }
        public string OthersDetails { get; set; }
    }
}
