//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblchqNo
    {
        public int chqNoId { get; set; }
        public Nullable<decimal> chqNo { get; set; }
        public string custName { get; set; }
        public string status { get; set; }
    }
}
