//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChqIssue
    {
        public int chqId { get; set; }
        public string actNo { get; set; }
        public string custName { get; set; }
        public Nullable<decimal> noOfLeaves { get; set; }
        public Nullable<decimal> chqStartNo { get; set; }
        public Nullable<decimal> chqEndNo { get; set; }
        public string chqIssuedBy { get; set; }
        public Nullable<System.DateTime> issuedDate { get; set; }
    }
}
