//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeposit
    {
        public int depositId { get; set; }
        public string branchName { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public string acctNo { get; set; }
        public string actName { get; set; }
        public string actType { get; set; }
        public Nullable<decimal> depositAmount { get; set; }
        public string Depositer { get; set; }
        public Nullable<decimal> currentBalance { get; set; }
    }
}
