//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoan
    {
        public int Loan_ID { get; set; }
        public string actNo { get; set; }
        public string cust_Name { get; set; }
        public Nullable<decimal> Monthly_Income { get; set; }
        public Nullable<decimal> Loan_Amount { get; set; }
        public string Loan_Type { get; set; }
        public Nullable<decimal> Interest_Rate { get; set; }
        public Nullable<decimal> Loan_Tenure_Years_ { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> YearlyInterest { get; set; }
        public Nullable<decimal> MonthlyInterest { get; set; }
        public Nullable<System.DateTime> Issued_Date { get; set; }
        public string Mortgage_Details { get; set; }
        public string Guarenteer_Name { get; set; }
        public string Address_Guarenteer_ { get; set; }
        public string Contact_Number { get; set; }
    }
}
